/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          50: '#fdf4f5',
          100: '#fbe7e9',
          200: '#f8d1d5',
          300: '#f3abb2',
          400: '#eb7985',
          500: '#df4659',
          600: '#cb2d43',
          700: '#aa1f33',
          800: '#8d1d2e',
          900: '#761c2b',
          950: '#420b14',
        },
        sage: {
          50: '#f4f7f5',
          100: '#e5ebe6',
          200: '#ccd9cf',
          300: '#a3baa9',
          400: '#769780',
          500: '#587b62',
          600: '#43614c',
          700: '#384f3f',
          800: '#2f4135',
          900: '#28362e',
          950: '#151e19',
        },
        "on-primary-fixed-variant": "#573974",
        "secondary": "#795465",
        "on-primary": "#ffffff",
        "error": "#ba1a1a",
        "surface-dim": "#dfd8de",
        "on-primary-container": "#60427d",
        "primary-fixed-dim": "#dcb8fc",
        "surface-bright": "#fff7fd",
        "secondary-fixed-dim": "#e9bacd",
        "on-tertiary-container": "#525300",
        "on-surface": "#1d1b1f",
        "surface": "#fff7fd",
        "on-tertiary-fixed": "#1d1d00",
        "tertiary": "#616211",
        "on-secondary-container": "#795465",
        "on-secondary-fixed": "#2e1221",
        "secondary-fixed": "#ffd8e7",
        "outline": "#7c747f",
        "tertiary-fixed-dim": "#cbcb71",
        "inverse-on-surface": "#f6eff5",
        "on-surface-variant": "#4b454e",
        "on-secondary": "#ffffff",
        "inverse-primary": "#dcb8fc",
        "primary": "#70518d",
        "surface-tint": "#70518d",
        "primary-fixed": "#f0dbff",
        "on-tertiary-fixed-variant": "#494900",
        "on-background": "#1d1b1f",
        "error-container": "#ffdad6",
        "surface-container-low": "#f9f1f7",
        "outline-variant": "#cdc3cf",
        "secondary-container": "#fdcde1",
        "surface-container": "#f3ecf2",
        "on-error": "#ffffff",
        "inverse-surface": "#322f34",
        "primary-container": "#d8b4f8",
        "surface-container-highest": "#e7e0e6",
        "surface-variant": "#e7e0e6",
        "tertiary-fixed": "#e8e78a",
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#c7c76d",
        "on-primary-fixed": "#290a45",
        "on-error-container": "#93000a",
        "background": "#fff7fd",
        "surface-container-high": "#ede6ec",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#5f3c4d",
      },
      fontFamily: {
        sans: ['var(--font-sans)', 'sans-serif'],
        display: ['var(--font-display)', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
